const searchData2 = [
  { id: 1, title: "Mathematics Past Questions", link: "/login" },
  { id: 2, title: "Physics Past Questions", link: "/login" },
  { id: 3, title: "English Past Questions", link: "/login" },
  { id: 4, title: "Chemistry Past Questions", link: "/login" },
  { id: 5, title: "Biology Past Questions", link: "/login" },
  { id: 6, title: "Crs Past Questions", link: "/login" },
  { id: 7, title: "Government Past Questions", link: "/login" },
  { id: 8, title: "Literature Past Questions", link: "/login" },
  { id: 9, title: "Commerce Past Questions", link: "/login" },
  { id: 10, title: "Accounting Past Questions", link: "/login" },
  { id: 11, title: "Economics Past Questions", link: "/login" },
  { id: 12, title: "Jamb Maths CBT", link: "/login" },
  { id: 13, title: "Jamb English CBT", link: "/login" },
  { id: 14, title: "Jamb Physics CBT", link: "/login" },
  { id: 15, title: "Jamb Chemistry CBT", link: "/login" },
  { id: 16, title: "Jamb Biology CBT", link: "/login" },
  { id: 17, title: "Jamb Commerce CBT", link: "/login" },
  { id: 18, title: "Jamb Crs CBT", link: "/login" },
  { id: 19, title: "Jamb Government CBT", link: "/login" },
  { id: 20, title: "Jamb Literature CBT", link: "/login" },
  { id: 21, title: "Jamb Accounting CBT", link: "/login" },
  { id: 22, title: "Jamb Economics CBT", link: "/login" },
  { id: 22, title: "Post-UTME Test", link: "/login" },
  { id: 22, title: "Unilag Post-UTME", link: "/login" },
  { id: 22, title: "Unical Post-UTME", link: "/login" },
  { id: 22, title: "EKSU Post-UTME", link: "/login" },
  { id: 22, title: "Unizik Post-UTME", link: "/login" },
];

export default searchData2;
